# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13vgKRWCPBSgCnsIy5kCawwaFWn9eUNvV
"""

#project Rock Paper Scissor

"""#paper defeats rock
#rock defeats scissor
#scissor defeats paper
#p+r=p
#r+s=r
#s+p=s

#step1:take human input
#step2:take computer input
#step3:check who is winner
#step4:add the score in the winner's account
#step5:ask if you want to repeat


"""

def takehumaninput():
  ch=input("enter the value between r/p/s :")
  ch=ch.lower()
  if (ch=='p' or ch=='r' or ch=='s'):
      return ch
  else:
      return takehumaninput()

takehumaninput()

import random
def generateComputerValue():
    ch= ""
    n=random.randint(0,3)
    if n==0:
        ch='s'
    elif n==1:
        ch='r'
    else:
        ch='p'
    return ch

generateComputerValue()

def checkWinner(humanInput,computerInput):
  winner=" "
  if humanInput=='p' and computerInput=='r':
    winner="human"
  elif humanInput=='p' and computerInput=='s':
    winner="computer"
  elif humanInput=='r' and computerInput=='s':
    winner="human"
  elif humanInput=='r' and computerInput=='p':
    winner="computer"
  elif humanInput=='s' and computerInput=='r':
    winner="computer"
  elif humanInput=='s' and computerInput=='p':
    winner="human"
  elif humanInput=='p' and computerInput=='p':
    winner="tie"
  elif humanInput=='s' and computerInput=='s':
    winner="tie"
  else:
    winner="tie"
  return winner
checkWinner('s','r')



def updatescore(user):
  if user=="human":
      score["human"]=score.get("human")+1
  elif user=="computer":
      score["computer"]=score.get("computer")+1
  else:
      score["tie"]=score.get("tie")+1

updatescore("computer")
score

score={"human":0,"computer":0,"tie":0}
playAgain="y"
while playAgain!="n":
  humanInput=takehumaninput()
  print("human input is:",humanInput)
  computerInput=generateComputerValue()
  print("computer input is:",computerInput)

  winner=checkWinner(humanInput,computerInput)
  print("winner of the round is:",winner)
  updatescore(winner)
  print("updated score is:",score)
  playAgain=input("would you like to play again (y/n)?")

!pip install xlrd2